#!/usr/bin/env bash
# VPS Security Hardening Script for Trading System
# Run as: ssh trader@187.77.132.195 'bash -s' < scripts/harden-vps.sh
# Or copy to VPS and run: sudo bash harden-vps.sh
#
# Prerequisites: nginx installed, trading-system.service running
# This script requires sudo privileges.

set -euo pipefail

echo "=== Trading System VPS Hardening ==="
echo ""

# ── 1. Close port 8080 (direct uvicorn bypass) ──────────────────────
echo "[1/6] Closing port 8080 in UFW..."
if sudo ufw status | grep -q "8080"; then
    sudo ufw delete allow 8080
    echo "  Port 8080 removed from UFW"
else
    echo "  Port 8080 already closed"
fi

# ── 2. Restrict webhook port 9000 to GitHub IPs only ────────────────
echo "[2/6] Restricting port 9000 to GitHub webhook IPs..."
# Remove the open rule first
if sudo ufw status | grep -q "9000.*ALLOW.*Anywhere"; then
    sudo ufw delete allow 9000 2>/dev/null || true
fi
# Add GitHub webhook IP ranges (from https://api.github.com/meta)
for cidr in 140.82.112.0/20 185.199.108.0/22 192.30.252.0/22 143.55.64.0/20; do
    sudo ufw allow from "$cidr" to any port 9000 comment "GitHub webhooks" 2>/dev/null || true
done
echo "  Port 9000 restricted to GitHub IP ranges"

# ── 3. Reload UFW ───────────────────────────────────────────────────
echo "[3/6] Reloading UFW..."
sudo ufw reload
echo "  UFW reloaded"

# ── 4. Create HTTP Basic Auth credentials ────────────────────────────
echo "[4/6] Setting up HTTP Basic Auth..."
if ! command -v htpasswd &>/dev/null; then
    sudo apt-get install -y apache2-utils
fi
if [ ! -f /etc/nginx/.htpasswd ]; then
    echo "  Creating /etc/nginx/.htpasswd"
    echo "  Enter a password for the dashboard (username: trader):"
    sudo htpasswd -c /etc/nginx/.htpasswd trader
    echo "  .htpasswd created"
else
    echo "  /etc/nginx/.htpasswd already exists"
    echo "  To reset: sudo htpasswd -c /etc/nginx/.htpasswd trader"
fi

# ── 5. Write hardened nginx config ───────────────────────────────────
echo "[5/6] Writing hardened nginx config..."

NGINX_CONF="/etc/nginx/sites-available/tradebot"
NGINX_CONF_BAK="${NGINX_CONF}.bak.$(date +%Y%m%d%H%M%S)"

# Backup existing config
if [ -f "$NGINX_CONF" ]; then
    sudo cp "$NGINX_CONF" "$NGINX_CONF_BAK"
    echo "  Backed up existing config to $NGINX_CONF_BAK"
fi

sudo tee "$NGINX_CONF" > /dev/null << 'NGINX_EOF'
# Trading Dashboard — Hardened nginx config
# Generated by scripts/harden-vps.sh

server {
    listen 80;
    server_name tradebot.codeandcraft.ai;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl http2;
    server_name tradebot.codeandcraft.ai;

    # SSL (managed by Certbot)
    ssl_certificate /etc/letsencrypt/live/tradebot.codeandcraft.ai/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tradebot.codeandcraft.ai/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    # Hide server version
    server_tokens off;

    # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; connect-src 'self' wss://tradebot.codeandcraft.ai https://www.google-analytics.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; frame-src 'self';" always;

    # HTTP Basic Auth for the entire site
    auth_basic "Trading Dashboard";
    auth_basic_user_file /etc/nginx/.htpasswd;

    # Rate limiting zone (defined in nginx.conf http block)
    # limit_req zone=dashboard burst=20 nodelay;

    # Proxy to uvicorn (localhost only)
    location / {
        proxy_pass http://127.0.0.1:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # WebSocket support
    location /ws {
        proxy_pass http://127.0.0.1:8080/ws;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
    }

    # Gzip compression for JSON and JS
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
    gzip_min_length 256;
}
NGINX_EOF

echo "  Hardened nginx config written"

# ── 6. Test and reload nginx ─────────────────────────────────────────
echo "[6/6] Testing and reloading nginx..."
if sudo nginx -t; then
    sudo systemctl reload nginx
    echo "  Nginx reloaded successfully"
else
    echo "  ERROR: nginx config test failed!"
    echo "  Restoring backup..."
    sudo cp "$NGINX_CONF_BAK" "$NGINX_CONF"
    sudo nginx -t && sudo systemctl reload nginx
    echo "  Backup restored"
    exit 1
fi

echo ""
echo "=== Hardening Complete ==="
echo ""
echo "Summary:"
echo "  - Port 8080: closed in UFW + uvicorn bound to 127.0.0.1"
echo "  - Port 9000: restricted to GitHub webhook IPs"
echo "  - Nginx: security headers, server_tokens off, HTTP/2, gzip"
echo "  - HTTP Basic Auth: enabled (username: trader)"
echo "  - OpenAPI schema: disabled in FastAPI"
echo "  - WebSocket: connection limit (20) + origin check"
echo ""
echo "Next steps:"
echo "  1. Restart trading system: sudo systemctl restart trading-system"
echo "  2. Test: curl -u trader:PASSWORD https://tradebot.codeandcraft.ai/api/portfolio"
echo "  3. Add to .env: DASHBOARD_ALLOWED_ORIGINS=https://tradebot.codeandcraft.ai"
echo ""
echo "To update Basic Auth password later:"
echo "  sudo htpasswd /etc/nginx/.htpasswd trader"
